version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
        - FLASK_ENV=development